server:
  port: ${SERVER_PORT:8087}
  shutdown: graceful

spring:
  application:
    name: notification-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/shopwave_notification}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  lifecycle:
    timeout-per-shutdown-phase: 30s

logging:
  level:
    root: INFO
    org.springframework.kafka: WARN
    org.apache.kafka: WARN
