version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: shopwave-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - shopwave_shopwave-network

  grafana:
    image: grafana/grafana:latest
    container_name: shopwave-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - shopwave_shopwave-network

networks:
  shopwave_shopwave-network:
    external: true
