apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: shopwave-namespace
type: Opaque
data:
  # Base64 encoded 'root' for postgres user/password
  POSTGRES_USER: "cm9vdA=="
  POSTGRES_PASSWORD: "cm9vdA=="
  SPRING_DATASOURCE_PASSWORD: "cm9vdA=="
