apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configmap
  namespace: shopwave-namespace
data:
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  SPRING_PROFILES_ACTIVE: "docker"
  JWT_EXPIRATION_MS: "900000"
  JWT_REFRESH_EXPIRATION_MS: "604800000"
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: "http://zipkin:9411/api/v2/spans"
  MANAGEMENT_TRACING_SAMPLING_PROBABILITY: "1.0"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,prometheus,metrics"
