server:
  port: ${SERVER_PORT:8082}
  shutdown: graceful

spring:
  application:
    name: product-service
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  cache:
    type: redis
    redis:
      time-to-live: 300000
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/shopwave_product}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  lifecycle:
    timeout-per-shutdown-phase: 30s
