apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-deployment
  namespace: shopwave-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: shopwave-order-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8084
          envFrom:
            - configMapRef:
                name: app-configmap
            - secretRef:
                name: jwt-secrets
            - secretRef:
                name: db-secrets
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: db-configmap
                  key: ORDER_DB_URL
            - name: PRODUCT_SERVICE_URL
              value: "http://product-service:8082"
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8084
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8084
            initialDelaySeconds: 0
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8084
            initialDelaySeconds: 0
            periodSeconds: 10
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
